// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "junmin.hong",
            "url": "https://github.com/junminhong",
            "email": "junminhong1110@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/trade": {
            "get": {
                "tags": [
                    "trade"
                ],
                "summary": "取得最新的Trade資料",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/http.aggTradeData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.aggTradeData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/http.data"
                },
                "stream": {
                    "type": "string"
                }
            }
        },
        "http.data": {
            "type": "object",
            "properties": {
                "E": {
                    "type": "integer"
                },
                "M": {
                    "type": "boolean"
                },
                "T": {
                    "type": "integer"
                },
                "a": {
                    "type": "integer"
                },
                "e": {
                    "type": "string"
                },
                "f": {
                    "type": "integer"
                },
                "l": {
                    "type": "integer"
                },
                "m": {
                    "type": "boolean"
                },
                "p": {
                    "type": "string"
                },
                "q": {
                    "type": "string"
                },
                "s": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Binance API",
	Description:      "好用的東西",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
